### ISSUE TITLE
upgradeCA.cert mandatory for branch 2.0.0 ?

### ISSUE THREAD

**Issue by deepikabhavnani** [armPelionEdge/meta-pelion-edge#87]
```
WARNING: ww-console-image-initramfs-init-1.0-r0 do_fetch: Failed to fetch URL file://upgradeCA.cert, attempting MIRRORS if available
ERROR: ww-console-image-initramfs-init-1.0-r0 do_fetch: Fetcher failure: Unable to find file file://upgradeCA.cert anywhere. The paths that were searched were:
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/poky
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/poky
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/poky
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/poky
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/raspberrypi3-mbl
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/raspberrypi3
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/raspberrypi3
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/raspberrypi3
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/raspberrypi3
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/armv7ve
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/armv7ve
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/armv7ve
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/armv7ve
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/rpi
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/rpi
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/rpi
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/rpi
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/allarch
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/allarch
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/allarch
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/allarch
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init-1.0/
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init/
    /home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/files/
    /home/deepika/poky/build/downloads
ERROR: ww-console-image-initramfs-init-1.0-r0 do_fetch: Fetcher failure for URL: 'file://upgradeCA.cert'. Unable to fetch URL from any source.
ERROR: ww-console-image-initramfs-init-1.0-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/deepika/poky/build/tmp/work/all-poky-linux/ww-console-image-initramfs-init/1.0-r0/temp/log.do_fetch.125
ERROR: Task (/home/deepika/poky/meta-pelion-edge/recipes-core/ww-console-image-initramfs-init/ww-console-image-initramfs-init_1.0.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1014 tasks of which 999 didn't need to be rerun and 1 failed.

```

**Comment by cmonr** [comment]
@deepikabhavnani I think so. An issue was brought up about a week or two ago in which a commit was added somewhere that added the requirement.

@costanic Do you recall that commit/issue?

**Comment by deepikabhavnani** [comment]
https://github.com/armPelionEdge/meta-pelion-edge/pull/28

**Comment by cmonr** [comment]
Huh. That's not what I was thinking at all.

**Comment by deepikabhavnani** [comment]
@theotherjimmy  informed me that development branch build instructions does have steps - https://github.com/armpelionedge/meta-pelion-edge/blob/dev/BUILD.md

But it is not very intuitive to have different instructions in branch readme, also if user decides to have an simple easy build following `build-pelion-edge` repo instructions it will not work.

**Comment by costanic** [comment]
@cmonr I think this is the issue you're thinking about: https://github.com/armPelionEdge/manifest-pelion-edge/issues/18 but that was for a different credentials file.  The file upgradeCA.cert mentioned here was added as a new requirement for a new feature in 2.0.

@deepikabhavnani The instructions are relative to the branch.  master branch instructions won't work for dev branch because of new features added in dev branch.  In addition, master branch (1.0 as of now) and dev branch (soon-to-be 2.0) currently differ so much because the READMEs in the various repos (manifest-pelion-edge, meta-pelion-edge, build-pelion-edge, etc.) were combined to reduce duplication of instructions in each of those READMEs.  The idea was that each repo's README should discuss the issues specific to that repo and then refer back to a central README https://github.com/armpelionedge/meta-pelion-edge/blob/dev/BUILD.md for instructions common to all repos.

**Comment by theotherjimmy** [comment]
@costanic That's great, but the issue here is that the central README was not easy to discover. Why is it not in the root? If it's so central (and this repo's whole job is to pull things together) then why is it not the README for this repo?

**Comment by costanic** [comment]
Not sure I understand.  It *is* in this repo and it is in the top level folder.  It's also linked from every other repo's README, including this one.  Feel free to make it more visible in any way you think would help.

**Comment by theotherjimmy** [comment]
I must have missed the top level folder bit. I had trouble finding these instructions yesterday, but I'm having trouble recalling why exactly. Sometimes hindsight makes that hard.

**Comment by theotherjimmy** [comment]
Perhaps it's because a central README is called BUILD?

**Comment by costanic** [comment]
The central README is still called README, but there is a 2nd markdown file called BUILD.md with the full set of instructions.  The central README.md links to BUILD.md, as do all the other repos.

But as you said, I think the problem we're experiencing here is that the docs on master branch are different from the docs on dev branch, largely due to the restructuring and consolidation of all the READMEs.  This should hopefully fix itself when 2.0 is released and merged into master.

**Comment by theotherjimmy** [comment]
Agreed.

What is master for?

**Comment by costanic** [comment]
master is the current stable release.

https://nvie.com/posts/a-successful-git-branching-model/

**Comment by theotherjimmy** [comment]
Then can we make `dev` the default branch to avoid this confusion?

**Comment by costanic** [comment]
That would create other confusion.  Glad to discuss in person, but ultimately these are your repos now so the branching policy is up to you.

**Comment by theotherjimmy** [comment]
Yeah, I'm not sure how to resolve this either. Both `dev` and `master` being default causes some confusion. Sorry for wording this in a prickly fashion, i meant only to figure out how we can avoid this issue in the future.

**Comment by costanic** [comment]
There's only 1 default: master.  It represents the current stable release.  When a customer checks out our repos, this is what they expect.

dev is where development occurs and may change daily.  Glad to discuss pros/cons of different approaches.

One thing that might help here is a note in the README about the purpose of the master and dev branches.

**Comment by theotherjimmy** [comment]
As a contributor writing a pull request on github, that's both unusual and inconvenient. As a contributor, I expect to clone, modify, fork, pull-request. In the model you have described, doing those operations in that order creates an incorrect pull-request, as it is:
 1) based on the stable branch instead of the development branch
 2) targeting the stable branch (and is therefore a "release PR")

As I have only interacted with this repo as a contributor, I have felt these pain points.

Noting the branching policy in the README would be really helpful; that's a great suggestion.

----------------

Nits about our taken branching policy below. Feel free to skip them.

From the article:
>We consider origin/master to be the main branch where the source code of HEAD always reflects a production-ready state.

That suggests that the development branch will not be in a production-ready state. Otherwise, it would be the master branch. 

Honestly, I prefer to have 1 branch with [The Not Rocket Science Rule Of Software Engineering](https://graydon2.dreamwidth.org/1597.html) applied. 
> automatically maintain a repository of code that always passes all the tests

I understand that at this point, that's not practical, so I think this is a reasonable branching strategy for this repo. I think we should continue with this branching strategy, and mark the README. Perhaps we can re-evaluate this decision at a later date.
